name: cicd

on: 
  push: 
    branches: 
      - master
  workflow_dispatch: 

jobs: 
  cicd: 
    runs-on: ubuntu-latest

    steps: 
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Lint Code Base
      uses: super-linter/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.AYUSH_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3        

    - name: build docker image
      run: docker built -t Ayush-vc/Myapp .
