name: cicd

on: 
  push: 
    branches: 
      - master
  workflow_dispatch: 

jobs: 
  cicd: 
    run-on: ubuntu-latest

    steps: 
    - name: checkout
      users: actions/checkout@v4
      
    - name: Lint Code Base
      uses: super-linter/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
